### ISSUE TITLE
How to change modulation to communicate with Heltec?

### ISSUE THREAD

**Issue by cnorman27** [LilyGO/TTGO-T-Beam#24]
I have the Heltec ESP32+OLED+LoRA module.  I can tell by using SDR# that the modulation is different but came find support for either one to make them communicate.

**Comment by anthonyvage** [comment]
Do you find a solution for your problem? I have the same problem.

**Comment by IZ0DZX** [comment]
Hello
I have not jet resolved the communication problem between Heltec board 1276x and TTGO T Beam. This is ok between the two Heltecs i own and also between the two T-Beams Where is the problem? please help
Thanks
Inviato da Libero Mail per Android mercoledì, 29 gennaio 2020, 01:22AM +01:00 da cnorman27  notifications@github.com :

**Comment by IZ0DZX** [comment]
Hello
I have not jet resolved the communication problem between Heltec board 1276x and TTGO T Beam. This is ok between the two Heltecs i own and also between the two T-Beams Where is the problem
--
Inviato da Libero Mail per Android mercoledì, 29 gennaio 2020, 01:20AM +01:00 da anthonyvage  notifications@github.com :

**Comment by anthonyvage** [comment]
I resolved the problem. Check the settings for spreading factor. It seems that heltec lora library has different default settings as the library ttgo uses.
