### ISSUE TITLE
Repetitive brownout reset upon power-on when battery is not connected 

### ISSUE THREAD

**Issue by lyusupov** [LilyGO/TTGO-T-Beam#3]
Hardware: **T-Beam T22_V06 20180706**
Firmware: **SoftRF 1.0-rc4+**
Power is supplied from **2A** rated 5V power source.
18650 battery is **not** connected.

The board does not start well.
UART log contains repetitive lines:

```
EEPROM version: 91
SX1276 RFIC is detected.
WARNING! Barometric pressure sensor is NOT detected.
INFO: TTGO T-Beam GPS module is detected.
WiFi config changed.
new SSID:
Hostname: SoftRF-c5d804
Wait for WiFi connection.
.....
Brownout detector was triggered
```

"+5V" supply voltage been measured at power switch point with assistance of a DSO shows significant
drop, quite similar to this picture:<br>
![](https://github.com/lyusupov/SoftRF/raw/master/documents/images/ESP32_WIFI_CALIB.jpg)

<br>

I had quite similar issue with my own ESP32-based design. I've resolved it by additional 1000uF capacitance. Please, read [this issue](https://github.com/lyusupov/ESP32-NODEMCU-ADAPTER/issues/3) for details.

<br>

Solution for this issue **is full up to you** !
I would just suggest you to try to increase value of **C47**:

![t-beam-tp5400-issue](https://user-images.githubusercontent.com/5849637/43686179-3802b414-98ca-11e8-8aed-2b3991d4a77c.JPG)

**Comment by jcwren** [comment]
I ran into the same thing today (just got my two boards yesterday). I happened to have a D-Link powered hub that does allow it to power up, but any of my other powered hubs do not. 

The lack of documentation is abysmal. Their "BBS" is down. No schematics. No indications as to what the LEDs are for. Seems to come with some soft of flight controller software installed, once you manage to guess the password to the soft AP ('12345678'). If they're to be taken seriously, they're going to need to put some effort into providing at least some minimal semblance of documentation.

**Comment by lyusupov** [comment]
They send schematics upon request.

AFAIK, 2 LEDs are for battery status. One is for GPS PPS. And one is software controlled (GPIO14)

They send the board with [my firmware](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII) been pre-installed, free of charge.
Quick start instructions are [here](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII.-Quick-start). 
Explanation of [Settings](https://github.com/lyusupov/SoftRF/wiki/Settings).

If you don't need built-in firmware - just overwrite it with your own one.

**Comment by lyusupov** [comment]
> Their "BBS" is down. 

I've noticed that TTGO BBS is up today.

**Comment by covra** [comment]
TTGo is terrible I have been looking for docs for days.. :(   Icant access to the AP with de "12345678"key with the SoftRF firmware, The Schematics are wrong... The LilyGo  repository  doesnt have explanation... what a mess!!

**Comment by jcwren** [comment]
Wait until you find out that your NEO-M6M GPS is probably a Chinese clone. I had to order a couple NEO-M8Ms to replace mine. I already had code that speaks UBX protocol to a uBlox GPS, and it wasn't working on the T-Beam. Determined it wasn't responding to NMEA commands, the UBX messages were ignored, etc. Swapped in the NEO-M8M's, *boom*, worked the first time.

**Comment by lemmingDev** [comment]
> They send schematics upon request.
> 
> AFAIK, 2 LEDs are for battery status. One is for GPS PPS. And one is software controlled (GPIO14)
> 
> They ship the board with [my firmware](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII) been pre-installed, **free of charge**.
> Quick start instructions are [here](https://github.com/lyusupov/SoftRF/wiki/Prime-Edition-MkII.-Quick-start).
> Explanation of [Settings](https://github.com/lyusupov/SoftRF/wiki/Settings).
> 
> If you don't need built-in firmware - just overwrite it with your own one.

Hi

Have ordered a whole class set of these for a highschool programming class.

Do these boards work fine off of a 18650 battery in the holder?

I have ttgo lora32 v1 and it works fine, but the v2 reboots due to brownout when starting bluetooth or wifi when using the same code on ttgo lora32 v2

Thanks

**Comment by covra** [comment]
The modules work fine with battery powered or with cap changed as lyusupov shows. I have two of them.

**Comment by lemmingDev** [comment]
Thanks for getting back to me.

Great to hear. 

All students will be getting a T-Beam,18650, USB cable, female pin headers and a 128x64px OLED.

I guess they won't experience any power issues as the 18650 will always be connected.

**Comment by covra** [comment]
Saving costs! xD

**Comment by lemmingDev** [comment]
All 32 boards work fine off battery

**Comment by astir13** [comment]
The boards work fine with a 18650 mounted, however 500mA via USB are not enough for permanent operation as SoftRF in Legacy mode, and the power supply is quite weak to power additional equipment like OLED, RS232 driver, without a battery as buffer. So my conclusion is you need a 18650 and a powerful power supply.

**Comment by hopexxx** [comment]
it is possible to replace the battery 18650 with lipo battery.. because the 18650 is to big and it make the casing also big

**Comment by lyusupov** [comment]
With appearance of V10 (a.k.a. V1.0) revision of T-Beam"s hardware this issue is no longer pertinent.
So I am closing it now...
