### ISSUE TITLE
Ports are displayed in wrong order on V1.0

### ISSUE THREAD

**Issue by Internetwurm** [LilyGO/TTGO-T-Beam#33]
Hello LilyGo,

this is a really nice product.
the pinout picture shows Port 21 and 22 in right order.
Picture and module writing is the same.

https://github.com/kizniche/ttgo-tbeam-ttn-tracker/blob/master/img/T-BEAM-Rev1-01.jpg

I am not really sure if this picture is done by LilyGo.
But the style looks similar to the picture for the earlier version. 

On this picture the module ordering 21 and 22 is the same but the writing right next to it display it in different order. 22 and 21 as also SDA and SCL are changed to the earlier version and pictures.
It may make a complictaed difference if somone doesn´t check more then twice and just relay to the picture. 

Thanks for this nice and good stuffed product.

regards
![image](https://user-images.githubusercontent.com/40214735/67338576-ae679900-f529-11e9-80e0-db1bb2a1a826.png)

**Comment by lyusupov** [comment]
Good catch!

I would suggest you to send your request to LilyGO **sales** staff.
( They create marketing info. Engineers don't do that. )
They typically fix the pictures within few days upon receive of customer's request.

Use communication method of the platform you've purchased the board onto (AliExpress, E-bay, Amazon, Banggood, …)

**Comment by Internetwurm** [comment]
Yes, i think it was obvious to post it here.
I will send the info to sales directly.

Thanks for reminding. ;-)
